-- Számlázás: vevők, számlák (számla / díjbekérő / sztornó), tételek, NAV napló.
-- Azonosítók: vevő VEVO-1023, számla SZ-2026-000187, díjbekérő DB-2026-000031.
-- Tárolás: date és numeric; a protokollban YYYY.MM.DD és vesszős tizedes.
-- Kívülről csak az egyedi szöveges protokollon keresztül érhető el.

create schema if not exists billing;

create sequence billing.vevo_seq start with 1001;
create sequence billing.szamla_seq;
create sequence billing.dijbekero_seq;

create function billing.kovetkezo_vevokod()
returns text
language sql
volatile
set search_path = ''
as $$
  select 'VEVO-' || nextval('billing.vevo_seq')::text;
$$;

-- A sztornó számla is a számla sorszámtartományból kap számot.
create function billing.kovetkezo_szamlaszam()
returns text
language sql
volatile
set search_path = ''
as $$
  select 'SZ-' || to_char(current_date, 'YYYY') || '-'
         || lpad(nextval('billing.szamla_seq')::text, 6, '0');
$$;

create function billing.kovetkezo_dijbekero_szam()
returns text
language sql
volatile
set search_path = ''
as $$
  select 'DB-' || to_char(current_date, 'YYYY') || '-'
         || lpad(nextval('billing.dijbekero_seq')::text, 6, '0');
$$;

create table billing.vevok (
  kod     text primary key default billing.kovetkezo_vevokod(),
  nev     text not null check (nev = upper(nev)),
  adoszam text not null unique,
  cim     text
);

create table billing.szamlak (
  szam         text primary key,
  tipus        text not null check (tipus in ('SZAMLA', 'DIJBEKERO', 'STORNO')),
  vevo_kod     text not null references billing.vevok (kod),
  rendeles_ref text,
  kelt         date not null default current_date,
  hatarido     date not null,
  netto        numeric(14,2) not null,
  afa          numeric(14,2) not null,
  brutto       numeric(14,2) not null,
  fizetve      boolean not null default false,
  fizetve_datum date,
  lejart       boolean not null default false,
  -- sztornó számlánál az eredeti számla száma; eredetinél a sztornózás jelzője
  eredeti_szam text references billing.szamlak (szam),
  sztornozva   boolean not null default false,
  szamlazz_id  text
);

create index szamlak_vevo_kod_idx on billing.szamlak (vevo_kod);
create index szamlak_rendeles_ref_idx on billing.szamlak (rendeles_ref);

create table billing.szamla_tetelek (
  id         integer generated by default as identity primary key,
  szam       text not null references billing.szamlak (szam) on delete cascade,
  sor        integer not null,
  megnevezes text not null,
  mennyiseg  numeric(12,2) not null,
  egysegar   numeric(14,2) not null,
  afa_kulcs  numeric(4,2) not null default 27
);

create index szamla_tetelek_szam_idx on billing.szamla_tetelek (szam);

-- Szimulált NAV online számla adatszolgáltatás naplója
create table billing.nav_log (
  id      integer generated by default as identity primary key,
  szam    text not null,
  muvelet text not null,
  statusz text not null,
  uzenet  text,
  ido     timestamptz not null default now()
);

-- Napi futás (pg_cron): lejárt, nem fizetett számlák megjelölése.
create function billing.jelol_lejart()
returns integer
language plpgsql
set search_path = ''
as $$
declare
  n integer;
begin
  update billing.szamlak
     set lejart = true
   where not fizetve
     and not lejart
     and not sztornozva
     and tipus <> 'STORNO'
     and hatarido < current_date;
  get diagnostics n = row_count;
  return n;
end;
$$;

grant usage on schema billing to service_role;
grant all on all tables in schema billing to service_role;
grant all on all sequences in schema billing to service_role;
alter default privileges in schema billing grant all on tables to service_role;
alter default privileges in schema billing grant all on sequences to service_role;
alter default privileges in schema billing grant execute on functions to service_role;

alter table billing.vevok          enable row level security;
alter table billing.szamlak        enable row level security;
alter table billing.szamla_tetelek enable row level security;
alter table billing.nav_log        enable row level security;
