-- Raktár: cikkek, foglalások, mozgások.
-- Azonosító: integer cikkszám (pl. 4711), idő: Unix epoch (bigint).
-- Kívülről csak a pgmq sorokon keresztül érhető el (inventory_commands / inventory_replies).

create schema if not exists inventory;

create function inventory.most_epoch()
returns bigint
language sql
stable
set search_path = ''
as $$
  select extract(epoch from now())::bigint;
$$;

create table inventory.items (
  cikk          integer primary key,
  megnevezes    text not null,
  keszlet       integer not null default 0 check (keszlet >= 0),
  foglalt       integer not null default 0 check (foglalt >= 0),
  min_keszlet   integer not null default 0 check (min_keszlet >= 0),
  updated_epoch bigint not null default inventory.most_epoch()
);

create table inventory.reservations (
  id            integer generated by default as identity primary key,
  cikk          integer not null references inventory.items (cikk),
  db            integer not null check (db > 0),
  ref           text not null,
  statusz       text not null default 'AKTIV'
                check (statusz in ('AKTIV', 'FELOLDVA', 'KIADVA')),
  created_epoch bigint not null default inventory.most_epoch()
);

create index reservations_ref_idx on inventory.reservations (ref);
create index reservations_cikk_idx on inventory.reservations (cikk);

create table inventory.movements (
  id    integer generated by default as identity primary key,
  cikk  integer not null references inventory.items (cikk),
  db    integer not null,
  tipus text not null check (tipus in ('BE', 'KI', 'VISSZARU', 'KORREKCIO')),
  ref   text,
  epoch bigint not null default inventory.most_epoch()
);

create index movements_cikk_idx on inventory.movements (cikk);

grant usage on schema inventory to service_role;
grant all on all tables in schema inventory to service_role;
grant all on all sequences in schema inventory to service_role;
alter default privileges in schema inventory grant all on tables to service_role;
alter default privileges in schema inventory grant all on sequences to service_role;
alter default privileges in schema inventory grant execute on functions to service_role;

alter table inventory.items        enable row level security;
alter table inventory.reservations enable row level security;
alter table inventory.movements    enable row level security;
