-- Ajánlatmotor: ajánlatok, tételek, sablonok.
-- Azonosító: AJ-2026-0042, dátum: date (YYYY-MM-DD), pénz: egész forint (bigint).
-- Kívülről csak JSON-RPC-n keresztül érhető el.

create schema if not exists quote;

create sequence quote.quote_seq;

create function quote.next_quote_id()
returns text
language sql
volatile
set search_path = ''
as $$
  select 'AJ-' || to_char(current_date, 'YYYY') || '-'
         || lpad(nextval('quote.quote_seq')::text, 4, '0');
$$;

create table quote.templates (
  id              integer generated by default as identity primary key,
  nev             text not null,
  fejlec          text,
  lablec          text,
  ervenyesseg_nap integer not null default 30 check (ervenyesseg_nap > 0)
);

create table quote.quotes (
  id                 text primary key default quote.next_quote_id()
                     check (id ~ '^AJ-[0-9]{4}-[0-9]{4,}$'),
  partner_id         uuid not null,
  template_id        integer references quote.templates (id),
  created_on         date not null default current_date,
  valid_until        date not null,
  status             text not null default 'PISZKOZAT'
                     check (status in ('PISZKOZAT', 'JOVAHAGYASRA_VAR', 'JOVAHAGYOTT',
                                       'ELFOGADVA', 'LEJART', 'ELUTASITVA')),
  total_net          bigint not null default 0,
  total_discount_pct numeric(5,2) not null default 0,
  approval_reason    text,
  approved_by        text,
  approved_on        date,
  order_ref          text
);

create index quotes_partner_id_idx on quote.quotes (partner_id);
create index quotes_status_idx on quote.quotes (status);

create table quote.quote_lines (
  id                integer generated by default as identity primary key,
  quote_id          text not null references quote.quotes (id) on delete cascade,
  product_code      text not null,
  qty               integer not null check (qty > 0),
  unit_price        bigint not null check (unit_price >= 0),
  line_discount_pct numeric(5,2) not null default 0
                    check (line_discount_pct between 0 and 100),
  line_net          bigint
);

create index quote_lines_quote_id_idx on quote.quote_lines (quote_id);

grant usage on schema quote to service_role;
grant all on all tables in schema quote to service_role;
grant all on all sequences in schema quote to service_role;
alter default privileges in schema quote grant all on tables to service_role;
alter default privileges in schema quote grant all on sequences to service_role;
alter default privileges in schema quote grant execute on functions to service_role;

alter table quote.templates   enable row level security;
alter table quote.quotes      enable row level security;
alter table quote.quote_lines enable row level security;
