-- Rendelések: törzsadat, tételek, foglalási hivatkozások, folyamattörténet, szállítás.
-- Azonosító: bigint 100001-től, hivatkozásban RND-100045. Idő: timestamptz (ISO).
-- Az életciklust a Flowable futtatja; itt a denormalizált aktuális állapot van.

create schema if not exists orders;

create table orders.orders (
  order_no            bigint generated by default as identity (start with 100001) primary key,
  quote_ref           text,
  partner_id          uuid not null,
  state               text not null default 'ROGZITETT'
                      check (state in ('ROGZITETT', 'JOVAHAGYOTT', 'TELJESITES_ALATT', 'SZALLITVA',
                                       'SZAMLAZVA', 'LEZART', 'LEMONDOTT')),
  process_instance_id text,
  invoice_ref         text,
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now()
);

create index orders_state_idx on orders.orders (state);
create index orders_invoice_ref_idx on orders.orders (invoice_ref);

create function orders.ref(p_order_no bigint)
returns text
language sql
immutable
set search_path = ''
as $$
  select 'RND-' || p_order_no::text;
$$;

create table orders.order_lines (
  id           bigint generated by default as identity primary key,
  order_no     bigint not null references orders.orders (order_no) on delete cascade,
  product_code text not null,
  qty          integer not null check (qty > 0),
  unit_price   numeric not null check (unit_price >= 0)
);

create index order_lines_order_no_idx on orders.order_lines (order_no);

create table orders.reservations_ref (
  id         bigint generated by default as identity primary key,
  order_no   bigint not null references orders.orders (order_no) on delete cascade,
  cikk       integer not null,
  db         integer not null,
  corr       text,
  created_at timestamptz not null default now()
);

create index reservations_ref_order_no_idx on orders.reservations_ref (order_no);

create table orders.process_history (
  id         bigint generated by default as identity primary key,
  order_no   bigint not null references orders.orders (order_no) on delete cascade,
  from_state text,
  to_state   text,
  action     text not null,
  ok         boolean not null default true,
  reason     text,
  ts         timestamptz not null default now()
);

create index process_history_order_no_idx on orders.process_history (order_no, ts);

create table orders.shipments (
  order_no       bigint primary key references orders.orders (order_no) on delete cascade,
  carrier        text not null default 'GLS',
  tracking_no    text,
  carrier_status text not null default 'FELVETELRE_VAR'
                 check (carrier_status in ('FELVETELRE_VAR', 'FELVEVE', 'UTON', 'KEZBESITVE', 'KESIK')),
  eta            timestamptz,
  updated_at     timestamptz not null default now()
);

-- Szállítás szimuláció (a fuvarozó „rendszere”), pg_cron hívja percenként.
-- Egy lépés: FELVETELRE_VAR -> FELVEVE -> UTON -> KEZBESITVE.
-- Felvett / úton lévő szállítmány kb. 15% eséllyel KESIK állapotba kerül,
-- ahonnan kb. 3 perc múlva megy tovább UTON állapotba.
create function orders.leptet_szallitasok()
returns integer
language plpgsql
set search_path = ''
as $$
declare
  s record;
  n integer := 0;
begin
  for s in
    select order_no, carrier_status, eta, updated_at
    from orders.shipments
    where carrier_status <> 'KEZBESITVE'
    for update
  loop
    if s.carrier_status = 'KESIK' then
      if s.updated_at < now() - interval '3 minutes' then
        update orders.shipments
           set carrier_status = 'UTON', updated_at = now()
         where order_no = s.order_no;
        n := n + 1;
      end if;
    elsif s.carrier_status in ('FELVEVE', 'UTON') and random() < 0.15 then
      update orders.shipments
         set carrier_status = 'KESIK',
             eta = coalesce(s.eta, now()) + interval '1 day',
             updated_at = now()
       where order_no = s.order_no;
      n := n + 1;
    else
      update orders.shipments
         set carrier_status = case s.carrier_status
                                when 'FELVETELRE_VAR' then 'FELVEVE'
                                when 'FELVEVE' then 'UTON'
                                when 'UTON' then 'KEZBESITVE'
                              end,
             updated_at = now()
       where order_no = s.order_no;
      n := n + 1;
    end if;
  end loop;
  return n;
end;
$$;

grant usage on schema orders to service_role;
grant all on all tables in schema orders to service_role;
grant all on all sequences in schema orders to service_role;
alter default privileges in schema orders grant all on tables to service_role;
alter default privileges in schema orders grant all on sequences to service_role;
alter default privileges in schema orders grant execute on functions to service_role;

alter table orders.orders           enable row level security;
alter table orders.order_lines      enable row level security;
alter table orders.reservations_ref enable row level security;
alter table orders.process_history  enable row level security;
alter table orders.shipments        enable row level security;
